### ISSUE TITLE
training code?

### ISSUE THREAD

**Issue by ppriyank** [BoomShakaY/AIM-CCReID#1]
Hello Authors,

Wondering if the training code will be released in near future?

**Comment by BoomShakaY** [comment]
Sorry for that. We are busy these months since several works are going on simultaneously. The training part will be released after careful re-organization when we are free.

**Comment by ppriyank** [comment]
Also, is it possible to upload the pre-trained weights to google drive, dropbox, or GitHub?

**Comment by 2845764980** [comment]
@ppriyank I think they will never release the train code. Hi bro, read these to papers source code you will get surprise. Counterfactual Attention Learning for Fine-Grained Visual Categorization and Re-identification and Clothes-Changing Person Re-identification with RGB Modality Only.

**Comment by BoomShakaY** [comment]
Sorry for the late reply due to so much going on. As more and more people are following this work, we have decided to release the preliminary version of the code after careful consideration, but there may still be some small bugs inside the code. We will gradually modify them later! We hope you understand, and thank you for your interest!

About the weights, we will consider uploading them on multiple platforms!
