### ISSUE TITLE
train

### ISSUE THREAD

**Issue by jiangliman** [BoomShakaY/AIM-CCReID#2]
Hello, when will you release the training code?

**Comment by 2845764980** [comment]
@jiangliman I think they will never release the train code. Hi bro, read these to papers source code you will get surprise. Counterfactual Attention Learning for Fine-Grained Visual Categorization and Re-identification and Clothes-Changing Person Re-identification with RGB Modality Only.

**Comment by BoomShakaY** [comment]
Sorry for the late reply due to so much going on. As more and more people are following this work, we have decided to release the preliminary version of the code after careful consideration, but there may still be some small bugs inside the code. We will gradually modify them later! We hope you understand, and thank you for your interest!
